# -*- coding: utf-8 -*-
"""Local app server for the EVA gallery (port 8765).

- Static files with no-cache headers
- GET  /api/list                 -> manifest as JSON (scans wallpapers dir)
- POST /api/upload?char=&name=   -> save image (body = raw bytes),
                                    generate thumbnail, rebuild manifest
- DELETE /api/delete?src=        -> delete image + thumbnail, rebuild manifest

Bind 127.0.0.1 only: upload/delete are trusted for the local user.
"""
import http.server
import json
import os
import subprocess
import sys
import threading
import time
import urllib.parse
import urllib.request
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent
PORT = 8765
IMG_EXT = {".jpg", ".jpeg", ".png", ".webp"}
CHARS = ("rei", "asuka", "misato")
MAX_BYTES = 30 * 1024 * 1024


def build_manifest():
    items = []
    wall = ROOT / "wallpapers"
    for name in sorted(os.listdir(wall)):
        stem, ext = os.path.splitext(name)
        if ext.lower() not in IMG_EXT or name.startswith("_"):
            continue
        char = next((c for c in CHARS if stem.startswith(c)), None)
        if char is None:
            continue
        try:
            with Image.open(wall / name) as im:
                w, h = im.size
        except Exception:
            continue
        items.append({
            "src": "wallpapers/" + name,
            "thumb": "wallpapers/thumbs/" + name,
            "char": char,
            "res": "%dx%d" % (w, h),
        })
    return items


VERSION = "v1.4.1"   # 与 GitHub Release tag 同步
GITHUB_API = "https://api.github.com/repos/Honor-Boop/asuka-rei-lianliankan/releases/latest"


def _github_token():
    """取本机 git 凭据里的 GitHub token（若有）：认证请求限额 5000/时，
    避免匿名 60/时 被限流导致更新检查失败。玩家机器没有凭据时返回 None，走匿名。"""
    try:
        out = subprocess.run(["git", "credential", "fill"],
                             input="protocol=https\nhost=github.com\n\n",
                             capture_output=True, text=True, timeout=8)
        for line in out.stdout.splitlines():
            if line.startswith("password="):
                return line.split("=", 1)[1].strip()
    except Exception:
        pass
    return None


def check_update():
    """查询 GitHub 最新 Release，返回是否有新版、下载地址与更新说明。"""
    try:
        headers = {"User-Agent": "eva-minigames-updater", "Accept": "application/vnd.github+json"}
        token = _github_token()
        if token:
            headers["Authorization"] = "token " + token
        req = urllib.request.Request(GITHUB_API, headers=headers)
        with urllib.request.urlopen(req, timeout=8) as r:
            d = json.loads(r.read().decode("utf-8"))
        tag = d.get("tag_name") or ""
        url = None
        for a in d.get("assets") or []:
            n = a.get("name") or ""
            if n.lower().endswith(".exe") and "setup" in n.lower():
                url = a.get("browser_download_url") or None
                break
        if not url and d.get("assets"):
            url = d["assets"][0].get("browser_download_url") or None
        body = d.get("body") or ""
        return {"ok": True, "latest": tag, "current": VERSION,
                "update": tag != VERSION and tag != "", "url": url,
                "notes": body[:3000]}
    except urllib.error.HTTPError as e:
        # 403 rate limit 等情况下返回可读错误（前端显示「检查失败」）
        reason = "rate_limited" if e.code == 403 else ("http_%d" % e.code)
        return {"ok": False, "error": reason}
    except Exception as e:
        return {"ok": False, "error": type(e).__name__}


def write_manifest():
    items = build_manifest()
    (ROOT / "wallpapers" / "manifest.js").write_text(
        "// auto-generated by serve.py\n"
        "window.WALLPAPER_LIST = " + json.dumps(items, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8")
    return items


def make_thumb(path):
    thumb_dir = ROOT / "wallpapers" / "thumbs"
    thumb_dir.mkdir(exist_ok=True)
    out = thumb_dir / path.name
    with Image.open(path) as im:
        im = im.convert("RGB")
        im.thumbnail((560, 10000), Image.LANCZOS)
        im.save(out, "JPEG", quality=82)


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *a, **kw):
        super().__init__(*a, directory=str(ROOT), **kw)

    def end_headers(self):
        self.send_header("Cache-Control", "no-store, no-cache, must-revalidate")
        self.send_header("Pragma", "no-cache")
        self.send_header("Expires", "0")
        super().end_headers()

    def log_message(self, fmt, *args):
        pass

    def send_json(self, obj, code=200):
        body = json.dumps(obj, ensure_ascii=False).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        path = urllib.parse.urlparse(self.path).path
        if path == "/api/list":
            return self.send_json(build_manifest())
        if path == "/api/version":
            return self.send_json({"version": VERSION})
        if path == "/api/update-check":
            return self.send_json(check_update())
        super().do_GET()

    def do_POST(self):
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path == "/api/restart":
            # 刷新程序：重启服务（托管模式由桌面宿主处理，仅告知）
            if MANAGED:
                self.send_json({"ok": True, "managed": True, "msg": "hosted"})
                return
            self.send_json({"ok": True, "msg": "restarting"})
            threading.Timer(0.5, restart_server).start()
            return
        if parsed.path != "/api/upload":
            return self.send_json({"ok": False, "error": "unknown endpoint"}, 404)
        q = urllib.parse.parse_qs(parsed.query)
        char = (q.get("char", ["misato"])[0]).lower()
        if char not in CHARS:
            char = "misato"
        name = os.path.basename(q.get("name", ["upload.jpg"])[0])
        ext = os.path.splitext(name)[1].lower()
        if ext not in IMG_EXT:
            return self.send_json({"ok": False, "error": "仅支持 JPG/PNG/WEBP"}, 400)
        length = int(self.headers.get("Content-Length") or 0)
        if length <= 0 or length > MAX_BYTES:
            return self.send_json({"ok": False, "error": "文件为空或超过 30MB"}, 400)
        data = self.rfile.read(length)

        wall = ROOT / "wallpapers"
        seq = 1
        while (wall / ("%s_upload_%02d%s" % (char, seq, ext))).exists():
            seq += 1
        fname = "%s_upload_%02d%s" % (char, seq, ext)
        (wall / fname).write_bytes(data)
        try:
            make_thumb(wall / fname)
        except Exception:
            pass
        manifest = write_manifest()
        return self.send_json({"ok": True, "file": fname, "count": len(manifest)})

    def do_DELETE(self):
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path != "/api/delete":
            return self.send_json({"ok": False, "error": "unknown endpoint"}, 404)
        q = urllib.parse.parse_qs(parsed.query)
        fname = os.path.basename(q.get("src", [""])[0])
        ext = os.path.splitext(fname)[1].lower()
        fp = ROOT / "wallpapers" / fname
        if ext not in IMG_EXT or not fp.is_file():
            return self.send_json({"ok": False, "error": "文件不存在"}, 404)
        os.remove(fp)
        tp = ROOT / "wallpapers" / "thumbs" / fname
        if tp.exists():
            os.remove(tp)
        manifest = write_manifest()
        return self.send_json({"ok": True, "count": len(manifest)})


# 托管模式：被桌面程序(desktop.py)嵌入时置 True——RESTART 端点不自杀宿主
MANAGED = False
_SERVER = None


def start_server(port=PORT):
    """启动本地服务（可被桌面程序嵌入），返回 httpd。"""
    global _SERVER
    write_manifest()
    httpd = http.server.ThreadingHTTPServer(("127.0.0.1", port), Handler)
    httpd.daemon_threads = True
    _SERVER = httpd
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    return httpd


def restart_server():
    """独立模式：自我重启为新进程；托管模式：交由宿主处理。"""
    if MANAGED:
        return
    try:
        flags = subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0
        subprocess.Popen([sys.executable, str(ROOT / "serve.py")],
                         cwd=str(ROOT), creationflags=flags)
    except Exception:
        pass
    time.sleep(0.6)
    os._exit(0)


if __name__ == "__main__":
    start_server()
    try:
        while True:
            time.sleep(3600)
    except KeyboardInterrupt:
        if _SERVER:
            _SERVER.shutdown()
