# -*- coding: utf-8 -*-
"""Local app server for the EVA gallery (port 8765).

- Static files with no-cache headers
- GET  /api/list                 -> manifest as JSON (scans wallpapers dir)
- POST /api/upload?char=&name=   -> save image (body = raw bytes),
                                    generate thumbnail, rebuild manifest
- DELETE /api/delete?src=        -> delete image + thumbnail, rebuild manifest

Bind 127.0.0.1 only: upload/delete are trusted for the local user.
"""
import http.server
import json
import os
import urllib.parse
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent
PORT = 8765
IMG_EXT = {".jpg", ".jpeg", ".png", ".webp"}
CHARS = ("rei", "asuka", "misato")
MAX_BYTES = 30 * 1024 * 1024


def build_manifest():
    items = []
    wall = ROOT / "wallpapers"
    for name in sorted(os.listdir(wall)):
        stem, ext = os.path.splitext(name)
        if ext.lower() not in IMG_EXT or name.startswith("_"):
            continue
        char = next((c for c in CHARS if stem.startswith(c)), None)
        if char is None:
            continue
        try:
            with Image.open(wall / name) as im:
                w, h = im.size
        except Exception:
            continue
        items.append({
            "src": "wallpapers/" + name,
            "thumb": "wallpapers/thumbs/" + name,
            "char": char,
            "res": "%dx%d" % (w, h),
        })
    return items


def write_manifest():
    items = build_manifest()
    (ROOT / "wallpapers" / "manifest.js").write_text(
        "// auto-generated by serve.py\n"
        "window.WALLPAPER_LIST = " + json.dumps(items, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8")
    return items


def make_thumb(path):
    thumb_dir = ROOT / "wallpapers" / "thumbs"
    thumb_dir.mkdir(exist_ok=True)
    out = thumb_dir / path.name
    with Image.open(path) as im:
        im = im.convert("RGB")
        im.thumbnail((560, 10000), Image.LANCZOS)
        im.save(out, "JPEG", quality=82)


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *a, **kw):
        super().__init__(*a, directory=str(ROOT), **kw)

    def end_headers(self):
        self.send_header("Cache-Control", "no-store, no-cache, must-revalidate")
        self.send_header("Pragma", "no-cache")
        self.send_header("Expires", "0")
        super().end_headers()

    def log_message(self, fmt, *args):
        pass

    def send_json(self, obj, code=200):
        body = json.dumps(obj, ensure_ascii=False).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        path = urllib.parse.urlparse(self.path).path
        if path == "/api/list":
            return self.send_json(build_manifest())
        super().do_GET()

    def do_POST(self):
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path != "/api/upload":
            return self.send_json({"ok": False, "error": "unknown endpoint"}, 404)
        q = urllib.parse.parse_qs(parsed.query)
        char = (q.get("char", ["misato"])[0]).lower()
        if char not in CHARS:
            char = "misato"
        name = os.path.basename(q.get("name", ["upload.jpg"])[0])
        ext = os.path.splitext(name)[1].lower()
        if ext not in IMG_EXT:
            return self.send_json({"ok": False, "error": "仅支持 JPG/PNG/WEBP"}, 400)
        length = int(self.headers.get("Content-Length") or 0)
        if length <= 0 or length > MAX_BYTES:
            return self.send_json({"ok": False, "error": "文件为空或超过 30MB"}, 400)
        data = self.rfile.read(length)

        wall = ROOT / "wallpapers"
        seq = 1
        while (wall / ("%s_upload_%02d%s" % (char, seq, ext))).exists():
            seq += 1
        fname = "%s_upload_%02d%s" % (char, seq, ext)
        (wall / fname).write_bytes(data)
        try:
            make_thumb(wall / fname)
        except Exception:
            pass
        manifest = write_manifest()
        return self.send_json({"ok": True, "file": fname, "count": len(manifest)})

    def do_DELETE(self):
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path != "/api/delete":
            return self.send_json({"ok": False, "error": "unknown endpoint"}, 404)
        q = urllib.parse.parse_qs(parsed.query)
        fname = os.path.basename(q.get("src", [""])[0])
        ext = os.path.splitext(fname)[1].lower()
        fp = ROOT / "wallpapers" / fname
        if ext not in IMG_EXT or not fp.is_file():
            return self.send_json({"ok": False, "error": "文件不存在"}, 404)
        os.remove(fp)
        tp = ROOT / "wallpapers" / "thumbs" / fname
        if tp.exists():
            os.remove(tp)
        manifest = write_manifest()
        return self.send_json({"ok": True, "count": len(manifest)})


if __name__ == "__main__":
    write_manifest()  # 启动时校准一次
    with http.server.ThreadingHTTPServer(("127.0.0.1", PORT), Handler) as httpd:
        httpd.serve_forever()
